name: QEAD
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.10.13
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - scipy
  - scikit-learn
  - jupyterlab
  - ipython
  - ipywidgets
  - dask
  - xgboost
  - lightgbm
  - catboost
  - tensorflow
  - keras
  - nltk
  - spacy
  - gensim
  - statsmodels
  - plotly
  - bokeh
  - altair
  - pymc3
  - sympy
  - beautifulsoup4
  - requests
  - scrapy
  - scikit-image
  - opencv
  - pydot
  - graphviz
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - tabulate

  # Pip-installed packages
  - pip:
      - torchsummary
      - pylatexenc
      - qiskit
      - qiskit-machine-learning
      - qiskit-finance
      - qiskit-aer
      - qiskit-aer-gpu
      - qiskit-algorithms
      - qiskit-optimization
      - pillow
      - watchlogs
      - wget
      - pyod
      - combo
      - nids-datasets
      - git+https://github.com/haowen-xu/tfsnippet
